# fly.toml app configuration file generated for halolight-api-go on 2025-12-10T09:32:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'halolight-api-go'
primary_region = 'iad'

[build]

[env]
  APP_PORT = "8000"
  APP_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.checks]
    [http_service.checks.http]
      path = "/health"
      interval = "30s"
      timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
